import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Header from "@/components/header";
import UserCard from "@/components/auth/user-card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-800`}
      >
        <div className="min-h-screen max-w-[1000px] mx-auto w-full flex flex-col">
          <Header />
          <div className="flex justify-between items-center gap-2 p-2 bg-gray-200">
            <Navbar />
            <UserCard />
          </div>
          <div className="flex-1 bg-primary-foreground">{children}</div>
        </div>
      </body>
    </html>
  );
}
